/*
Task 1

If we list all the natural numbers below 10 that are multiples of 3 or 5,
we get 3, 5, 6, and 9. The sum of these numbers is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
*/

export const task1 = (limit) => {
    return Array.from({ length: limit }, (_, i) => i)
        .filter(n => n % 3 === 0 || n % 5 === 0)
        .reduce((sum, n) => sum + n, 0);
};

/*
Task 2

Each new term in the Fibonacci sequence is generated by adding
the previous two terms. Starting with 1 and 2, the first 10 terms are:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all even-valued terms in the Fibonacci sequence
whose values do not exceed four million.
*/

export const task2 = (limit) => {
    let a = 1,
        b = 2,
        sum = 0;

    while (b <= limit) {
        if (b % 2 === 0) sum += b;
        [a, b] = [b, a + b];
    }

    return sum;
};
